env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  indent: ['warn', 2, { 'SwitchCase': 1 }]
  linebreak-style: 0
  quotes:
    - warn
    - single
  semi:
    - warn
    - never
  no-unused-vars:
    - warn
